# Generated by Django 3.2.9 on 2021-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
